version: '3'

services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=etl_db
    networks:
      - my-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: etl_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 1m30s
      timeout: 10s
      retries: 5
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
